package com.mycompany.easytrip.telas.componentes;

public class ConfirmarReservaPanel extends javax.swing.JPanel {

    public ConfirmarReservaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dataEntradaLabel = new javax.swing.JLabel();
        dataSaidaLabel = new javax.swing.JLabel();
        precoDiariaLabel = new javax.swing.JLabel();
        quantidadeDeDiasLabel = new javax.swing.JLabel();
        precoTotalLabel = new javax.swing.JLabel();
        realizarReservaButton = new javax.swing.JButton();
        dataEntradaField = new javax.swing.JTextField();
        dataSaidaField = new javax.swing.JTextField();
        precoDiariaField = new javax.swing.JTextField();
        quantidadeDiasField = new javax.swing.JTextField();
        precoTotalField = new javax.swing.JTextField();
        quantidadeHospedeLabel = new javax.swing.JLabel();
        quantidadeHospedeField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridBagLayout());

        dataEntradaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        dataEntradaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataEntradaLabel.setLabelFor(dataEntradaField);
        dataEntradaLabel.setText("Data de entrada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(dataEntradaLabel, gridBagConstraints);

        dataSaidaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        dataSaidaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataSaidaLabel.setLabelFor(dataSaidaField);
        dataSaidaLabel.setText("Data de saída:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(dataSaidaLabel, gridBagConstraints);

        precoDiariaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        precoDiariaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoDiariaLabel.setLabelFor(precoDiariaField);
        precoDiariaLabel.setText("Preço diária: R$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(precoDiariaLabel, gridBagConstraints);

        quantidadeDeDiasLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        quantidadeDeDiasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidadeDeDiasLabel.setLabelFor(quantidadeDeDiasLabel);
        quantidadeDeDiasLabel.setText("Quantidade de dias:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(quantidadeDeDiasLabel, gridBagConstraints);

        precoTotalLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        precoTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoTotalLabel.setLabelFor(precoTotalField);
        precoTotalLabel.setText("Preço Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(precoTotalLabel, gridBagConstraints);

        realizarReservaButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        realizarReservaButton.setText("Realizar Reserva");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(realizarReservaButton, gridBagConstraints);

        dataEntradaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataEntradaField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(dataEntradaField, gridBagConstraints);

        dataSaidaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataSaidaField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(dataSaidaField, gridBagConstraints);

        precoDiariaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        precoDiariaField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(precoDiariaField, gridBagConstraints);

        quantidadeDiasField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        quantidadeDiasField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(quantidadeDiasField, gridBagConstraints);

        precoTotalField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        precoTotalField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(precoTotalField, gridBagConstraints);

        quantidadeHospedeLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        quantidadeHospedeLabel.setText("Quantidade de hóspedes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(quantidadeHospedeLabel, gridBagConstraints);

        quantidadeHospedeField.setFont(new java.awt.Font("JetBrainsMonoNL NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(quantidadeHospedeField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataEntradaField;
    private javax.swing.JLabel dataEntradaLabel;
    private javax.swing.JTextField dataSaidaField;
    private javax.swing.JLabel dataSaidaLabel;
    private javax.swing.JTextField precoDiariaField;
    private javax.swing.JLabel precoDiariaLabel;
    private javax.swing.JTextField precoTotalField;
    private javax.swing.JLabel precoTotalLabel;
    private javax.swing.JLabel quantidadeDeDiasLabel;
    private javax.swing.JTextField quantidadeDiasField;
    private javax.swing.JTextField quantidadeHospedeField;
    private javax.swing.JLabel quantidadeHospedeLabel;
    private javax.swing.JButton realizarReservaButton;
    // End of variables declaration//GEN-END:variables
}
