package com.mycompany.easytrip.telas.componentes;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

public class EscolherDataPanel extends javax.swing.JPanel {

    public EscolherDataPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dataLabel = new javax.swing.JLabel();
        disponibilidadeDataChosser = new com.toedter.calendar.JDateChooser();

        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));
        setLayout(new java.awt.GridBagLayout());

        dataLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataLabel.setText("Data:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(dataLabel, gridBagConstraints);

        disponibilidadeDataChosser.setDate(new Date());
        disponibilidadeDataChosser.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(disponibilidadeDataChosser, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public LocalDate getDataEscolhida(){
        return disponibilidadeDataChosser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataLabel;
    private com.toedter.calendar.JDateChooser disponibilidadeDataChosser;
    // End of variables declaration//GEN-END:variables
}
