package com.mycompany.easytrip.telas.componentes;

public class GruposListaPanel extends javax.swing.JPanel {

    public GruposListaPanel() {
        initComponents();
        completarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeGrupoLabel = new javax.swing.JLabel();
        funcaoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 4, 5, 0));

        nomeGrupoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        nomeGrupoLabel.setText("Nome de grupo");
        add(nomeGrupoLabel);

        funcaoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        funcaoLabel.setText("Membro");
        add(funcaoLabel);
    }// </editor-fold>//GEN-END:initComponents

    private void completarComponentes(){
        GerenciarGrupoButton gerenciarButton = new GerenciarGrupoButton();
        SairGrupoButton sairButton = new SairGrupoButton();
        
        this.add(gerenciarButton);
        this.add(sairButton);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel funcaoLabel;
    private javax.swing.JLabel nomeGrupoLabel;
    // End of variables declaration//GEN-END:variables
}
