package com.mycompany.easytrip.telas.componentes;

import com.mycompany.easytrip.dominio.entidades.Hospedagem;

public class HospedagemCadastradasPanel extends javax.swing.JPanel {

    private Hospedagem hospedagem;
    
    public HospedagemCadastradasPanel() {
        initComponents();
    }
    
    public HospedagemCadastradasPanel(Hospedagem hospedagem){
        this.hospedagem = hospedagem;
        initComponents();
        completarComponentesHospedagem();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        avaliacaoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 6, 2, 0));

        tituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tituloLabel.setText("Título");
        tituloLabel.setMinimumSize(new java.awt.Dimension(60, 17));
        tituloLabel.setPreferredSize(new java.awt.Dimension(90, 17));
        add(tituloLabel);

        tipoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tipoLabel.setText("Tipo");
        add(tipoLabel);

        avaliacaoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        avaliacaoLabel.setText("Avaliação");
        add(avaliacaoLabel);
    }// </editor-fold>//GEN-END:initComponents
    
    private void completarComponentesHospedagem(){
        tituloLabel.setText(hospedagem.getTitulo());
        tipoLabel.setText(hospedagem.getTipo().name());
        avaliacaoLabel.setText(String.valueOf(hospedagem.getNotaAvaliacao()));
        
        ReservasDaHospedagemButton reservasButton = new ReservasDaHospedagemButton();
        GerenciarHospedagemButton gerenciarButton = new GerenciarHospedagemButton();
        DeletarHospedagemButton deletarButton = new DeletarHospedagemButton();
        
        this.add(reservasButton);
        this.add(gerenciarButton);
        this.add(deletarButton);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avaliacaoLabel;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
