package com.mycompany.easytrip.telas.componentes;

import com.mycompany.easytrip.telas.TelaPrincipal;
import javax.swing.SwingUtilities;

public class HospedagemVisualizacaoPanel extends javax.swing.JPanel {

    public HospedagemVisualizacaoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        enderecoLabel = new javax.swing.JLabel();
        avaliacaoButton = new javax.swing.JLabel();
        verMaisButton = new javax.swing.JButton();
        precoLabel = new javax.swing.JLabel();
        favoritarButton = new javax.swing.JButton();
        imagemPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(163, 187, 229));
        setMinimumSize(new java.awt.Dimension(220, 220));
        setPreferredSize(new java.awt.Dimension(220, 220));
        setLayout(new java.awt.GridBagLayout());

        enderecoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 10)); // NOI18N
        enderecoLabel.setText("Rua recanto das dunas, cabo frio");
        enderecoLabel.setMaximumSize(new java.awt.Dimension(200, 16));
        enderecoLabel.setMinimumSize(new java.awt.Dimension(200, 16));
        enderecoLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(enderecoLabel, gridBagConstraints);

        avaliacaoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        avaliacaoButton.setText("5.0");
        avaliacaoButton.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(avaliacaoButton, gridBagConstraints);

        verMaisButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        verMaisButton.setText("Ver mais");
        verMaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMaisButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(verMaisButton, gridBagConstraints);

        precoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        precoLabel.setText("R$ 200,00");
        precoLabel.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(precoLabel, gridBagConstraints);

        favoritarButton.setBorderPainted(false);
        favoritarButton.setContentAreaFilled(false);
        favoritarButton.setLabel("❤");
        favoritarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(favoritarButton, gridBagConstraints);

        javax.swing.GroupLayout imagemPanelLayout = new javax.swing.GroupLayout(imagemPanel);
        imagemPanel.setLayout(imagemPanelLayout);
        imagemPanelLayout.setHorizontalGroup(
            imagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        imagemPanelLayout.setVerticalGroup(
            imagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 140;
        add(imagemPanel, gridBagConstraints);

        tituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 10)); // NOI18N
        tituloLabel.setText("Casa perto da praia");
        tituloLabel.setMaximumSize(new java.awt.Dimension(200, 16));
        tituloLabel.setMinimumSize(new java.awt.Dimension(200, 16));
        tituloLabel.setPreferredSize(new java.awt.Dimension(200, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(tituloLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void verMaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMaisButtonActionPerformed
        // TODO add your handling code here:
        mudarParaTelaDetalhesHospedagem();
    }//GEN-LAST:event_verMaisButtonActionPerformed
    
    
    private void mudarParaTelaDetalhesHospedagem(){
        TelaPrincipal telaPrincipal = (TelaPrincipal)SwingUtilities.getWindowAncestor(this);
        telaPrincipal.mudarParaTelaDetalhesHospedagem();
    }
    
    private void favoritarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoritarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favoritarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avaliacaoButton;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JButton favoritarButton;
    private javax.swing.JPanel imagemPanel;
    private javax.swing.JLabel precoLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton verMaisButton;
    // End of variables declaration//GEN-END:variables
}
