/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.easytrip.telas.componentes;

/**
 *
 * @author victo
 */
public class RankGrupoPanel extends javax.swing.JPanel {

    /**
     * Creates new form RankGrupoPanel
     */
    public RankGrupoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hospedagemFavoritasGrupoVisuPanel1 = new com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 3));

        jLabel1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1 -");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1);
        add(hospedagemFavoritasGrupoVisuPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel hospedagemFavoritasGrupoVisuPanel1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
