package com.mycompany.easytrip.telas.componentes;

public class ReservasListaPendentesPanel extends javax.swing.JPanel {

    public ReservasListaPendentesPanel() {
        initComponents();
        completarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 3, 2, 0));

        jLabel1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        jLabel1.setText("Titulo");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        jLabel2.setText("Q. hospedes");
        add(jLabel2);

        jLabel3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        jLabel3.setText("R$ 0000.00");
        add(jLabel3);
    }// </editor-fold>//GEN-END:initComponents

    private void completarComponentes(){
        DetalhesReservaButton button = new DetalhesReservaButton();
        this.add(button);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
