package com.mycompany.easytrip.telas.reservas;

import com.mycompany.easytrip.controllers.RealizarReservaController;
import com.mycompany.easytrip.dominio.entidades.Disponibilidade;
import com.mycompany.easytrip.telas.TelaPrincipal;
import com.mycompany.easytrip.telas.componentes.DisponibilidadeParaReservarPanel;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.SwingUtilities;

public class TelaRealizarReserva extends javax.swing.JPanel {
    private RealizarReservaController controller;
    private int hospedagemId;
    private List<Disponibilidade> disponibilidades;
    public TelaRealizarReserva() {
        initComponents();
    }
    
    public TelaRealizarReserva(int hospedagemId){
        this.hospedagemId = hospedagemId;
        this.controller = new RealizarReservaController(this);
        controller.carregarHospedagem(hospedagemId);

        initComponents();
        
        this.confirmarReservaPanel1.realizarReservaButton.addActionListener((ActionEvent e) -> {
            controller.finalizarReserva();
        });
    }
    
    public int getHospedagemId(){
        return this.hospedagemId;
    }
    
    public void setListaDisponibilidade(List<Disponibilidade> disponibilidades){
        this.disponibilidades = disponibilidades;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        disponibilidadeParaReservarPanel1 = new DisponibilidadeParaReservarPanel(disponibilidades);
        continuarButton = new javax.swing.JButton();
        cancelarButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        confirmarReservaPanel1 = new com.mycompany.easytrip.telas.componentes.ConfirmarReservaPanel();
        cancelarButton2 = new javax.swing.JButton();
        anteriorButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(163, 187, 229));

        continuarButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        continuarButton.setText("Continuar");
        continuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButtonActionPerformed(evt);
            }
        });

        cancelarButton1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cancelarButton1.setText("Cancelar");
        cancelarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelarButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continuarButton)
                .addContainerGap())
            .addComponent(disponibilidadeParaReservarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(disponibilidadeParaReservarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuarButton)
                    .addComponent(cancelarButton1))
                .addGap(14, 14, 14))
        );

        add(jPanel1, "card3");

        jPanel2.setBackground(new java.awt.Color(163, 187, 229));

        cancelarButton2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cancelarButton2.setText("Cancelar");
        cancelarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton2ActionPerformed(evt);
            }
        });

        anteriorButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton.setText("Anterior");
        anteriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelarButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anteriorButton)
                .addContainerGap())
            .addComponent(confirmarReservaPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(confirmarReservaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton2)
                    .addComponent(anteriorButton))
                .addContainerGap())
        );

        add(jPanel2, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton1ActionPerformed
        // TODO add your handling code here:
        voltarParaDetalhesHospedagem();
    }//GEN-LAST:event_cancelarButton1ActionPerformed

    private void continuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButtonActionPerformed
        // TODO add your handling code here:
        controller.continuarReserva();
    }//GEN-LAST:event_continuarButtonActionPerformed

    private void anteriorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButtonActionPerformed
        // TODO add your handling code here:
        anteriorCardLayout();
    }//GEN-LAST:event_anteriorButtonActionPerformed

    private void cancelarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton2ActionPerformed
        // TODO add your handling code here:
        voltarParaDetalhesHospedagem();
    }//GEN-LAST:event_cancelarButton2ActionPerformed

    private void voltarParaDetalhesHospedagem(){
        TelaPrincipal telaPrincipal = (TelaPrincipal)SwingUtilities.getWindowAncestor(this);
        telaPrincipal.mudarParaTelaDetalhesHospedagem(hospedagemId, false);
    }
    
    public int getUsuarioLogadoId(){
        TelaPrincipal telaPrincipal = (TelaPrincipal)SwingUtilities.getWindowAncestor(this);
        return telaPrincipal.getUsuarioLogado();
    }
    
    public void proximoCardLayout(){
        CardLayout layout = (CardLayout) this.getLayout();
        layout.next(this);
    }
    
    private void anteriorCardLayout(){
        CardLayout layout = (CardLayout) this.getLayout();
        layout.previous(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorButton;
    private javax.swing.JButton cancelarButton1;
    private javax.swing.JButton cancelarButton2;
    public com.mycompany.easytrip.telas.componentes.ConfirmarReservaPanel confirmarReservaPanel1;
    private javax.swing.JButton continuarButton;
    public com.mycompany.easytrip.telas.componentes.DisponibilidadeParaReservarPanel disponibilidadeParaReservarPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
