package com.mycompany.easytrip.telas.reservas;

import com.mycompany.easytrip.controllers.MinhasReservasController;

public class TelaMinhasReservas extends javax.swing.JPanel {
    private MinhasReservasController controller;
    
    public TelaMinhasReservas() {
        initComponents();
    }
    
    public TelaMinhasReservas(int usuarioId){
        initComponents();
        this.controller = new MinhasReservasController(this);
        
        controller.carregarReservas(usuarioId);
    }
    
    public int receberReservaSelecionada(){
        int linha = reservaTable.getSelectedRow();
        int reservaId = 0;
        
        if (linha != -1)
            reservaId = (Integer) reservaTable.getValueAt(linha, 0);
        
        return reservaId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        hospedagensTituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservaTable = new javax.swing.JTable();
        detalhesReservaButton1 = new com.mycompany.easytrip.telas.componentes.DetalhesReservaButton();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridBagLayout());

        hospedagensTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        hospedagensTituloLabel.setText("Minhas reservas");
        hospedagensTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(hospedagensTituloLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        add(jSeparator1, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 80));

        reservaTable.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        reservaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título Hospedagem", "Status", "Data de Entrada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        reservaTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reservaTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reservaTable.setShowGrid(false);
        jScrollPane1.setViewportView(reservaTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 150.0;
        gridBagConstraints.weighty = 150.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(jScrollPane1, gridBagConstraints);

        detalhesReservaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalhesReservaButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        add(detalhesReservaButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void detalhesReservaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalhesReservaButton1ActionPerformed
        // TODO add your handling code here:
        controller.mudarParaTelaDetalhesReserva();
    }//GEN-LAST:event_detalhesReservaButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.mycompany.easytrip.telas.componentes.DetalhesReservaButton detalhesReservaButton1;
    private javax.swing.JLabel hospedagensTituloLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable reservaTable;
    // End of variables declaration//GEN-END:variables
}
