package com.mycompany.easytrip.telas.reservas;

import com.mycompany.easytrip.controllers.DetalhesReservaController;
import com.mycompany.easytrip.telas.TelaPrincipal;
import javax.swing.SwingUtilities;

public class TelaDetalhesReserva extends javax.swing.JPanel {
    private int reservaId;
    private int usuarioId;
    private DetalhesReservaController controller;
    
    public TelaDetalhesReserva() {
        initComponents();
    }
    
    public TelaDetalhesReserva(int usuarioId,int reservaId){
        initComponents();
        this.reservaId = reservaId;
        this.usuarioId = usuarioId;
        this.controller = new DetalhesReservaController(this);
        controller.carregarReserva(this.reservaId);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        minhasFavoritasTituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tituloHospedagemLabel = new javax.swing.JLabel();
        enderecoLabel = new javax.swing.JLabel();
        dataEntradaLabel = new javax.swing.JLabel();
        dataSaidaLabel = new javax.swing.JLabel();
        quantidadeDiasLabel = new javax.swing.JLabel();
        precoDiariaLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        avaliacaoLabel = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        enderecoField = new javax.swing.JTextField();
        dataEntradaField = new javax.swing.JTextField();
        dataSaidaField = new javax.swing.JTextField();
        quantidadeDiasField = new javax.swing.JTextField();
        precoDiariaField = new javax.swing.JFormattedTextField();
        statusField = new javax.swing.JTextField();
        avaliacaoField = new javax.swing.JTextField();
        avaliarButton = new javax.swing.JButton();
        cancelarReservaButton = new javax.swing.JButton();
        quantidadeHospedeLabel = new javax.swing.JLabel();
        quantidadeHospedeField = new javax.swing.JTextField();
        voltarButton1 = new com.mycompany.easytrip.telas.componentes.VoltarButton();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridBagLayout());

        minhasFavoritasTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        minhasFavoritasTituloLabel.setText("Reserva");
        minhasFavoritasTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        add(minhasFavoritasTituloLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(jSeparator1, gridBagConstraints);

        tituloHospedagemLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tituloHospedagemLabel.setLabelFor(tituloField);
        tituloHospedagemLabel.setText("Titulo Hospedagem:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(tituloHospedagemLabel, gridBagConstraints);

        enderecoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        enderecoLabel.setLabelFor(enderecoField);
        enderecoLabel.setText("Endereço Hospedagem:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(enderecoLabel, gridBagConstraints);

        dataEntradaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataEntradaLabel.setLabelFor(dataEntradaField);
        dataEntradaLabel.setText("Data de entrada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(dataEntradaLabel, gridBagConstraints);

        dataSaidaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataSaidaLabel.setLabelFor(dataSaidaField);
        dataSaidaLabel.setText("Data de saída:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(dataSaidaLabel, gridBagConstraints);

        quantidadeDiasLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        quantidadeDiasLabel.setLabelFor(quantidadeDiasField);
        quantidadeDiasLabel.setText("Quantidade de dias:");
        quantidadeDiasLabel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(quantidadeDiasLabel, gridBagConstraints);

        precoDiariaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        precoDiariaLabel.setLabelFor(precoDiariaField);
        precoDiariaLabel.setText("Preço diária:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(precoDiariaLabel, gridBagConstraints);

        statusLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        statusLabel.setLabelFor(statusField);
        statusLabel.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(statusLabel, gridBagConstraints);

        avaliacaoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        avaliacaoLabel.setLabelFor(avaliacaoField);
        avaliacaoLabel.setText("Avaliação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(avaliacaoLabel, gridBagConstraints);

        tituloField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tituloField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(tituloField, gridBagConstraints);

        enderecoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(enderecoField, gridBagConstraints);

        dataEntradaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataEntradaField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(dataEntradaField, gridBagConstraints);

        dataSaidaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataSaidaField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(dataSaidaField, gridBagConstraints);

        quantidadeDiasField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        quantidadeDiasField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(quantidadeDiasField, gridBagConstraints);

        precoDiariaField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        precoDiariaField.setEnabled(false);
        precoDiariaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(precoDiariaField, gridBagConstraints);

        statusField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        statusField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(statusField, gridBagConstraints);

        avaliacaoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        avaliacaoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        avaliacaoField.setText("0.0");
        avaliacaoField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(avaliacaoField, gridBagConstraints);

        avaliarButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        avaliarButton.setText("Avaliar");
        avaliarButton.setEnabled(false);
        avaliarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(avaliarButton, gridBagConstraints);

        cancelarReservaButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cancelarReservaButton.setText("Cancelar reserva");
        cancelarReservaButton.setEnabled(false);
        cancelarReservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarReservaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(cancelarReservaButton, gridBagConstraints);

        quantidadeHospedeLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        quantidadeHospedeLabel.setText("Quantidade de Hóspedes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(quantidadeHospedeLabel, gridBagConstraints);

        quantidadeHospedeField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        quantidadeHospedeField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(quantidadeHospedeField, gridBagConstraints);

        voltarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        add(voltarButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton1ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton1ActionPerformed

    private void cancelarReservaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarReservaButtonActionPerformed
        // TODO add your handling code here:
        controller.cancelarReserva(reservaId);
    }//GEN-LAST:event_cancelarReservaButtonActionPerformed

    private void avaliarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarButtonActionPerformed
        // TODO add your handling code here:
        controller.avaliarReserva(reservaId);
    }//GEN-LAST:event_avaliarButtonActionPerformed

    private void voltarPagina(){
        TelaPrincipal telaPrincipal = (TelaPrincipal)SwingUtilities.getWindowAncestor(this);
        
        telaPrincipal.voltarPagina();
    }
    
    public int getUsuarioLogado(){
        return usuarioId;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField avaliacaoField;
    private javax.swing.JLabel avaliacaoLabel;
    public javax.swing.JButton avaliarButton;
    public javax.swing.JButton cancelarReservaButton;
    public javax.swing.JTextField dataEntradaField;
    private javax.swing.JLabel dataEntradaLabel;
    public javax.swing.JTextField dataSaidaField;
    private javax.swing.JLabel dataSaidaLabel;
    public javax.swing.JTextField enderecoField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel minhasFavoritasTituloLabel;
    public javax.swing.JFormattedTextField precoDiariaField;
    private javax.swing.JLabel precoDiariaLabel;
    public javax.swing.JTextField quantidadeDiasField;
    private javax.swing.JLabel quantidadeDiasLabel;
    public javax.swing.JTextField quantidadeHospedeField;
    private javax.swing.JLabel quantidadeHospedeLabel;
    public javax.swing.JTextField statusField;
    private javax.swing.JLabel statusLabel;
    public javax.swing.JTextField tituloField;
    private javax.swing.JLabel tituloHospedagemLabel;
    private com.mycompany.easytrip.telas.componentes.VoltarButton voltarButton1;
    // End of variables declaration//GEN-END:variables
}
