package com.mycompany.easytrip.telas.reservas;

public class TelaReservasDaHospedagem extends javax.swing.JPanel {

    public TelaReservasDaHospedagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        minhasFavoritasTituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        reservasListaPanel2 = new com.mycompany.easytrip.telas.componentes.ReservasListaPanel();
        legendaPanel = new javax.swing.JPanel();
        tituloLegendaLabel = new javax.swing.JLabel();
        statusLegendaLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        reservasListaPanel3 = new com.mycompany.easytrip.telas.componentes.ReservasListaPanel();
        reservasListaPanel4 = new com.mycompany.easytrip.telas.componentes.ReservasListaPanel();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridBagLayout());

        minhasFavoritasTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        minhasFavoritasTituloLabel.setText("Reservas da hospedagem");
        minhasFavoritasTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        add(minhasFavoritasTituloLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(reservasListaPanel2, gridBagConstraints);

        legendaPanel.setBackground(new java.awt.Color(163, 187, 229));
        legendaPanel.setLayout(new java.awt.GridLayout(1, 3, 2, 0));

        tituloLegendaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        tituloLegendaLabel.setText("Titulo");
        legendaPanel.add(tituloLegendaLabel);

        statusLegendaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        statusLegendaLabel.setText("Status");
        legendaPanel.add(statusLegendaLabel);
        legendaPanel.add(filler1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(legendaPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(reservasListaPanel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(reservasListaPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel legendaPanel;
    private javax.swing.JLabel minhasFavoritasTituloLabel;
    private com.mycompany.easytrip.telas.componentes.ReservasListaPanel reservasListaPanel2;
    private com.mycompany.easytrip.telas.componentes.ReservasListaPanel reservasListaPanel3;
    private com.mycompany.easytrip.telas.componentes.ReservasListaPanel reservasListaPanel4;
    private javax.swing.JLabel statusLegendaLabel;
    private javax.swing.JLabel tituloLegendaLabel;
    // End of variables declaration//GEN-END:variables
}
