package com.mycompany.easytrip.telas.grupos;

import javax.swing.JOptionPane;

public class TelaFavoritasGrupo extends javax.swing.JPanel {

    public TelaFavoritasGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        favoritasTituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        anteriorButton = new javax.swing.JButton();
        proximoButton = new javax.swing.JButton();
        selecionarGrupoButton = new javax.swing.JButton();
        hospedagemFavoritasGrupoVisuPanel1 = new com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel();
        hospedagemFavoritasGrupoVisuPanel2 = new com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel();
        hospedagemFavoritasGrupoVisuPanel3 = new com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel();
        hospedagemFavoritasGrupoVisuPanel4 = new com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(163, 187, 229));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        favoritasTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        favoritasTituloLabel.setText("Favoritas de [Nome do grupo]");
        favoritasTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        jPanel1.add(favoritasTituloLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(jSeparator1, gridBagConstraints);

        anteriorButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton.setText("Anterior");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        jPanel1.add(anteriorButton, gridBagConstraints);

        proximoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton.setText("Próximo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        jPanel1.add(proximoButton, gridBagConstraints);

        selecionarGrupoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        selecionarGrupoButton.setText("Selecionar grupo");
        selecionarGrupoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarGrupoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        jPanel1.add(selecionarGrupoButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(hospedagemFavoritasGrupoVisuPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(hospedagemFavoritasGrupoVisuPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(hospedagemFavoritasGrupoVisuPanel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        jPanel1.add(hospedagemFavoritasGrupoVisuPanel4, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarGrupoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarGrupoButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showOptionDialog(null, "Escolha o grupo: ", "Escolha grupo", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, new String[]{"Grupo 1", "Grupo 2", "Grupo3"}, "Grupo 1");
    }//GEN-LAST:event_selecionarGrupoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorButton;
    private javax.swing.JLabel favoritasTituloLabel;
    private com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel hospedagemFavoritasGrupoVisuPanel1;
    private com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel hospedagemFavoritasGrupoVisuPanel2;
    private com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel hospedagemFavoritasGrupoVisuPanel3;
    private com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel hospedagemFavoritasGrupoVisuPanel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton proximoButton;
    private javax.swing.JButton selecionarGrupoButton;
    // End of variables declaration//GEN-END:variables
}
