package com.mycompany.easytrip.telas.grupos;

import com.mycompany.easytrip.controllers.GerenciarGrupoController;
import com.mycompany.easytrip.telas.TelaPrincipal;
import javax.swing.SwingUtilities;

public class TelaGerenciarGrupo extends javax.swing.JPanel {
    private int usuarioId;
    private int grupoId;
    private GerenciarGrupoController controller;
    
    public TelaGerenciarGrupo() {
        initComponents();
    }
    
    public TelaGerenciarGrupo(int usuarioId, int grupoId){
        initComponents();
        this.usuarioId = usuarioId;
        this.grupoId = grupoId;
        this.controller = new GerenciarGrupoController(this);
        
        controller.carregarGrupo(grupoId);
    }
    
    public int receberParticipanteSelecionado(){
        int linha = membroTable.getSelectedRow();
        int participanteId = 0;

        if(linha != -1)
            participanteId = (Integer)membroTable.getValueAt(linha, 0);
        
        return participanteId;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        minhasFavoritasTituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nomeGrupoLabel = new javax.swing.JLabel();
        nomeGrupoField = new javax.swing.JTextField();
        totalPessoasLabel = new javax.swing.JLabel();
        totalPessoasField = new javax.swing.JTextField();
        membrosLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        membroTable = new javax.swing.JTable();
        voltarButton1 = new com.mycompany.easytrip.telas.componentes.VoltarButton();
        removerUsuarioButton = new javax.swing.JButton();
        alterarFuncaoButton = new javax.swing.JButton();
        novoMembroButton = new javax.swing.JButton();
        alterarQuantidadeAcompanhantesButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(163, 187, 229));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new java.awt.GridBagLayout());

        minhasFavoritasTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        minhasFavoritasTituloLabel.setText("Grupo");
        minhasFavoritasTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        add(minhasFavoritasTituloLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(jSeparator1, gridBagConstraints);

        nomeGrupoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        nomeGrupoLabel.setLabelFor(nomeGrupoField);
        nomeGrupoLabel.setText("Nome do grupo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(nomeGrupoLabel, gridBagConstraints);

        nomeGrupoField.setEnabled(false);
        nomeGrupoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeGrupoFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(nomeGrupoField, gridBagConstraints);

        totalPessoasLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        totalPessoasLabel.setLabelFor(totalPessoasField);
        totalPessoasLabel.setText("Total de pessoas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(totalPessoasLabel, gridBagConstraints);

        totalPessoasField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(totalPessoasField, gridBagConstraints);

        membrosLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        membrosLabel.setLabelFor(membroTable);
        membrosLabel.setText("Membros:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(membrosLabel, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(470, 420));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(470, 420));

        membroTable.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        membroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Bruce Wayne", "Responsável", "2"},
                {"2", "Peter Parker", "Membro", "1"}
            },
            new String [] {
                "Id", "Nome", "Função", "Acompanhantes"
            }
        ));
        jScrollPane1.setViewportView(membroTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(jScrollPane1, gridBagConstraints);

        voltarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(voltarButton1, gridBagConstraints);

        removerUsuarioButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        removerUsuarioButton.setText("Remover usuário");
        removerUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerUsuarioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(removerUsuarioButton, gridBagConstraints);

        alterarFuncaoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        alterarFuncaoButton.setText("Alterar função");
        alterarFuncaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncaoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(alterarFuncaoButton, gridBagConstraints);

        novoMembroButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        novoMembroButton.setText("Novo membro");
        novoMembroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoMembroButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(novoMembroButton, gridBagConstraints);

        alterarQuantidadeAcompanhantesButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        alterarQuantidadeAcompanhantesButton.setText("Alterar acompanhantes");
        alterarQuantidadeAcompanhantesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarQuantidadeAcompanhantesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(alterarQuantidadeAcompanhantesButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeGrupoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeGrupoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeGrupoFieldActionPerformed

    private void voltarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton1ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton1ActionPerformed

    private void alterarFuncaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncaoButtonActionPerformed
        // TODO add your handling code here:
        controller.alterarFuncao(grupoId);
    }//GEN-LAST:event_alterarFuncaoButtonActionPerformed

    private void removerUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerUsuarioButtonActionPerformed
        // TODO add your handling code here:
        controller.removerUsuario(grupoId);
    }//GEN-LAST:event_removerUsuarioButtonActionPerformed

    private void novoMembroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoMembroButtonActionPerformed
        // TODO add your handling code here:
        controller.adicionarNovoMembro(grupoId);
    }//GEN-LAST:event_novoMembroButtonActionPerformed

    private void alterarQuantidadeAcompanhantesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarQuantidadeAcompanhantesButtonActionPerformed
        // TODO add your handling code here:
        controller.alterarQuantidadeDeAcompanhantes(grupoId);
    }//GEN-LAST:event_alterarQuantidadeAcompanhantesButtonActionPerformed

    private void voltarPagina(){
        TelaPrincipal telaPrincipal = (TelaPrincipal)SwingUtilities.getWindowAncestor(this);
        telaPrincipal.mudarParaTelaVisualizarGrupos();
    }
    
    public int getUsuarioLogadoId(){
        return usuarioId;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton alterarFuncaoButton;
    public javax.swing.JButton alterarQuantidadeAcompanhantesButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable membroTable;
    private javax.swing.JLabel membrosLabel;
    private javax.swing.JLabel minhasFavoritasTituloLabel;
    public javax.swing.JTextField nomeGrupoField;
    private javax.swing.JLabel nomeGrupoLabel;
    public javax.swing.JButton novoMembroButton;
    public javax.swing.JButton removerUsuarioButton;
    public javax.swing.JTextField totalPessoasField;
    private javax.swing.JLabel totalPessoasLabel;
    private com.mycompany.easytrip.telas.componentes.VoltarButton voltarButton1;
    // End of variables declaration//GEN-END:variables
}
