package com.mycompany.easytrip.telas.grupos;

public class TelaRankingGrupo extends javax.swing.JPanel {

    public TelaRankingGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        hospedagensTituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        hospedagemFavoritasGrupoVisuPanel1 = new com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel();
        posicaoRankingLabel1 = new javax.swing.JLabel();
        posicaoRankingLabel2 = new javax.swing.JLabel();
        hospedagemFavoritasGrupoVisuPanel2 = new com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(163, 187, 229));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        hospedagensTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        hospedagensTituloLabel.setText("Ranking");
        hospedagensTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        jPanel1.add(hospedagensTituloLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(hospedagemFavoritasGrupoVisuPanel1, gridBagConstraints);

        posicaoRankingLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        posicaoRankingLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicaoRankingLabel1.setText("1-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(posicaoRankingLabel1, gridBagConstraints);

        posicaoRankingLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        posicaoRankingLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicaoRankingLabel2.setText("2-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(posicaoRankingLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(hospedagemFavoritasGrupoVisuPanel2, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel hospedagemFavoritasGrupoVisuPanel1;
    private com.mycompany.easytrip.telas.componentes.HospedagemFavoritasGrupoVisuPanel hospedagemFavoritasGrupoVisuPanel2;
    private javax.swing.JLabel hospedagensTituloLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel posicaoRankingLabel1;
    private javax.swing.JLabel posicaoRankingLabel2;
    // End of variables declaration//GEN-END:variables
}
