package com.mycompany.easytrip.telas.grupos;

import com.mycompany.easytrip.controllers.RankingGrupoController;

public class TelaRankingGrupo extends javax.swing.JPanel {
    public static final int QUANTIDADE_HOSPEDAGEM_RANKING = 10; 
    private int usuarioId;
    private RankingGrupoController controller;

    public TelaRankingGrupo() {
        initComponents();
    }
    
    public TelaRankingGrupo(int usuarioId){
        initComponents();
        this.usuarioId = usuarioId;
        this.controller = new RankingGrupoController(this);
        
        controller.carregarHospedagens(usuarioId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        visualizacaoPanel = new javax.swing.JPanel();
        rankingTituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        selecionarGrupoButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setToolTipText("");

        visualizacaoPanel.setBackground(new java.awt.Color(163, 187, 229));
        visualizacaoPanel.setLayout(new java.awt.GridBagLayout());

        rankingTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        rankingTituloLabel.setText("Ranking");
        rankingTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        visualizacaoPanel.add(rankingTituloLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        visualizacaoPanel.add(jSeparator1, gridBagConstraints);

        selecionarGrupoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        selecionarGrupoButton.setText("Selecionar grupo");
        selecionarGrupoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarGrupoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        visualizacaoPanel.add(selecionarGrupoButton, gridBagConstraints);

        jScrollPane1.setViewportView(visualizacaoPanel);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarGrupoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarGrupoButtonActionPerformed
        // TODO add your handling code here:
        controller.alterarGrupo(usuarioId);
    }//GEN-LAST:event_selecionarGrupoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel rankingTituloLabel;
    private javax.swing.JButton selecionarGrupoButton;
    public javax.swing.JPanel visualizacaoPanel;
    // End of variables declaration//GEN-END:variables
}
