package com.mycompany.easytrip.telas.grupos;

public class TelaGerenciarGrupo extends javax.swing.JPanel {

    public TelaGerenciarGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        minhasFavoritasTituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nomeGrupoLabel = new javax.swing.JLabel();
        nomeGrupoField = new javax.swing.JTextField();
        qAcompanhantesLabel = new javax.swing.JLabel();
        qAcompanhantesField = new javax.swing.JTextField();
        membrosLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        membroTable = new javax.swing.JTable();
        voltarButton1 = new com.mycompany.easytrip.telas.componentes.VoltarButton();
        removerUsuarioButton = new javax.swing.JButton();
        alterarFuncaoButton = new javax.swing.JButton();
        novoMrmbroButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(163, 187, 229));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new java.awt.GridBagLayout());

        minhasFavoritasTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        minhasFavoritasTituloLabel.setText("Grupo");
        minhasFavoritasTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        add(minhasFavoritasTituloLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(jSeparator1, gridBagConstraints);

        nomeGrupoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        nomeGrupoLabel.setLabelFor(nomeGrupoField);
        nomeGrupoLabel.setText("Nome do grupo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(nomeGrupoLabel, gridBagConstraints);

        nomeGrupoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeGrupoFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(nomeGrupoField, gridBagConstraints);

        qAcompanhantesLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        qAcompanhantesLabel.setLabelFor(qAcompanhantesField);
        qAcompanhantesLabel.setText("Minha q. acompanhantes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(qAcompanhantesLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(qAcompanhantesField, gridBagConstraints);

        membrosLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        membrosLabel.setLabelFor(membroTable);
        membrosLabel.setText("Membros:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(membrosLabel, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(470, 420));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(470, 420));

        membroTable.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        membroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bruce Wayne", "Responsável", "2"},
                {"Peter Parker", "Membro", "1"}
            },
            new String [] {
                "Nome", "Função", "Acompanhantes"
            }
        ));
        jScrollPane1.setViewportView(membroTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(voltarButton1, gridBagConstraints);

        removerUsuarioButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        removerUsuarioButton.setText("Remover usuário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(removerUsuarioButton, gridBagConstraints);

        alterarFuncaoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        alterarFuncaoButton.setText("Alterar função");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(alterarFuncaoButton, gridBagConstraints);

        novoMrmbroButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        novoMrmbroButton.setText("Novo membro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(novoMrmbroButton, gridBagConstraints);

        salvarButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        salvarButton.setText("Salvar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        add(salvarButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeGrupoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeGrupoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeGrupoFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarFuncaoButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable membroTable;
    private javax.swing.JLabel membrosLabel;
    private javax.swing.JLabel minhasFavoritasTituloLabel;
    private javax.swing.JTextField nomeGrupoField;
    private javax.swing.JLabel nomeGrupoLabel;
    private javax.swing.JButton novoMrmbroButton;
    private javax.swing.JTextField qAcompanhantesField;
    private javax.swing.JLabel qAcompanhantesLabel;
    private javax.swing.JButton removerUsuarioButton;
    private javax.swing.JButton salvarButton;
    private com.mycompany.easytrip.telas.componentes.VoltarButton voltarButton1;
    // End of variables declaration//GEN-END:variables
}
