package com.mycompany.easytrip.telas.hospedagem;

import java.awt.CardLayout;

public class TelaCriarHospedagem extends javax.swing.JPanel {

    public TelaCriarHospedagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        informacoesPanel = new javax.swing.JPanel();
        informacoesTituloLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        descricaoLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        capacidadeMaximaLabel = new javax.swing.JLabel();
        precoDiariaLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        checkInLabel = new javax.swing.JLabel();
        checkOutLabel = new javax.swing.JLabel();
        tipoField = new javax.swing.JTextField();
        capacidadeMaximaField = new javax.swing.JTextField();
        precoDiariaField = new javax.swing.JTextField();
        proximoButton = new javax.swing.JButton();
        checkInField = new javax.swing.JTextField();
        checkOutField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        enderecoPanel = new javax.swing.JPanel();
        cepLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        ruaLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        complementoLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        enderecoTituloLabel = new javax.swing.JLabel();
        cepField = new javax.swing.JTextField();
        numeroField = new javax.swing.JTextField();
        ruaField = new javax.swing.JTextField();
        bairroField = new javax.swing.JTextField();
        complementoField = new javax.swing.JTextField();
        cidadeField = new javax.swing.JTextField();
        estadoField = new javax.swing.JTextField();
        anteriorButton = new javax.swing.JButton();
        criarButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.CardLayout());

        informacoesPanel.setBackground(new java.awt.Color(163, 187, 229));
        informacoesPanel.setLayout(new java.awt.GridBagLayout());

        informacoesTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        informacoesTituloLabel.setText("Informações");
        informacoesTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(informacoesTituloLabel, gridBagConstraints);

        tituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tituloLabel.setLabelFor(tituloField);
        tituloLabel.setText("Titulo:");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tituloLabel, gridBagConstraints);

        tituloField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tituloField, gridBagConstraints);

        descricaoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        descricaoLabel.setLabelFor(descricaoTextArea);
        descricaoLabel.setText("Descrição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(descricaoLabel, gridBagConstraints);

        tipoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tipoLabel.setLabelFor(tipoField);
        tipoLabel.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tipoLabel, gridBagConstraints);

        capacidadeMaximaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        capacidadeMaximaLabel.setLabelFor(capacidadeMaximaField);
        capacidadeMaximaLabel.setText("Capacidade Máxima:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(capacidadeMaximaLabel, gridBagConstraints);

        precoDiariaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        precoDiariaLabel.setLabelFor(precoDiariaField);
        precoDiariaLabel.setText("Preço Diária:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(precoDiariaLabel, gridBagConstraints);

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N

        descricaoTextArea.setColumns(20);
        descricaoTextArea.setRows(5);
        jScrollPane.setViewportView(descricaoTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 5);
        informacoesPanel.add(jScrollPane, gridBagConstraints);

        checkInLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        checkInLabel.setLabelFor(checkInField);
        checkInLabel.setText("CheckIn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkInLabel, gridBagConstraints);

        checkOutLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        checkOutLabel.setLabelFor(checkOutField);
        checkOutLabel.setText("CheckOut:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkOutLabel, gridBagConstraints);

        tipoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tipoField, gridBagConstraints);

        capacidadeMaximaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(capacidadeMaximaField, gridBagConstraints);

        precoDiariaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(precoDiariaField, gridBagConstraints);

        proximoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton.setText("Próximo");
        proximoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(proximoButton, gridBagConstraints);

        checkInField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkInField, gridBagConstraints);

        checkOutField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkOutField, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        informacoesPanel.add(jSeparator1, gridBagConstraints);

        add(informacoesPanel, "card2");

        enderecoPanel.setBackground(new java.awt.Color(163, 187, 229));
        enderecoPanel.setLayout(new java.awt.GridBagLayout());

        cepLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cepLabel.setLabelFor(cepField);
        cepLabel.setText("Cep:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cepLabel, gridBagConstraints);

        numeroLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        numeroLabel.setLabelFor(numeroField);
        numeroLabel.setText("Numero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(numeroLabel, gridBagConstraints);

        ruaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        ruaLabel.setLabelFor(ruaField);
        ruaLabel.setText("Rua:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(ruaLabel, gridBagConstraints);

        bairroLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        bairroLabel.setLabelFor(bairroField);
        bairroLabel.setText("Bairro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(bairroLabel, gridBagConstraints);

        complementoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        complementoLabel.setLabelFor(complementoField);
        complementoLabel.setText("Complemento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(complementoLabel, gridBagConstraints);

        cidadeLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cidadeLabel.setLabelFor(cidadeField);
        cidadeLabel.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cidadeLabel, gridBagConstraints);

        estadoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        estadoLabel.setLabelFor(estadoField);
        estadoLabel.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(estadoLabel, gridBagConstraints);

        enderecoTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        enderecoTituloLabel.setText("Endereço");
        enderecoTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(enderecoTituloLabel, gridBagConstraints);

        cepField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cepField, gridBagConstraints);

        numeroField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(numeroField, gridBagConstraints);

        ruaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(ruaField, gridBagConstraints);

        bairroField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(bairroField, gridBagConstraints);

        complementoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(complementoField, gridBagConstraints);

        cidadeField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cidadeField, gridBagConstraints);

        estadoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(estadoField, gridBagConstraints);

        anteriorButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton.setText("Anterior");
        anteriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(anteriorButton, gridBagConstraints);

        criarButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        criarButton.setText("Criar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(criarButton, gridBagConstraints);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        enderecoPanel.add(jSeparator3, gridBagConstraints);

        add(enderecoPanel, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void proximoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButtonActionPerformed
        // TODO add your handling code here:
        proximoCardLayout();
    }//GEN-LAST:event_proximoButtonActionPerformed

    private void anteriorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButtonActionPerformed
        // TODO add your handling code here:
        anteriorCardLayout();
    }//GEN-LAST:event_anteriorButtonActionPerformed

    private void proximoCardLayout(){
        CardLayout layout = (CardLayout) this.getLayout();
        layout.next(this);
    }
    
    private void anteriorCardLayout(){
        CardLayout layout = (CardLayout) this.getLayout();
        layout.previous(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorButton;
    private javax.swing.JTextField bairroField;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField capacidadeMaximaField;
    private javax.swing.JLabel capacidadeMaximaLabel;
    private javax.swing.JTextField cepField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JTextField checkInField;
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JTextField checkOutField;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JTextField cidadeField;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField complementoField;
    private javax.swing.JLabel complementoLabel;
    private javax.swing.JButton criarButton;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextArea descricaoTextArea;
    private javax.swing.JPanel enderecoPanel;
    private javax.swing.JLabel enderecoTituloLabel;
    private javax.swing.JTextField estadoField;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JPanel informacoesPanel;
    private javax.swing.JLabel informacoesTituloLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField numeroField;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField precoDiariaField;
    private javax.swing.JLabel precoDiariaLabel;
    private javax.swing.JButton proximoButton;
    private javax.swing.JTextField ruaField;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JTextField tipoField;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tituloField;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
