package com.mycompany.easytrip.telas.hospedagem;

import com.mycompany.easytrip.controllers.VisualizarFavoritasHospedeController;

public class TelaFavoritasHospede extends javax.swing.JPanel {
    private VisualizarFavoritasHospedeController controller;
    private int pagina = 0;
    public static final int QUANTIDADE_POR_PAGINA = 8;
    private int usuarioId;
    
    public TelaFavoritasHospede() {
        initComponents();
    }
    
    public TelaFavoritasHospede(int usuarioId) {
        initComponents();
        desligarBotaoAnterior();
        this.usuarioId = usuarioId;
        this.controller = new VisualizarFavoritasHospedeController(this);
        
        controller.carregarHospedagens(usuarioId);
    }
    
    public int getPaginaAtual(){
        return pagina;
    }

    public void desligarBotaoAnterior(){
        this.anteriorButton.setVisible(false);
        this.anteriorButton.setEnabled(false);
    }
    
    public void ligarBotaoAnterior(){
        this.anteriorButton.setVisible(true);
        this.anteriorButton.setEnabled(true);
    }
    
    public void atualizarPagina(){
        this.revalidate();
        this.repaint();
    }
    
    public void incrementarPagina(){
        pagina++;
    }
    
    public void decrementarPagina(){
        pagina--;
    }
    
    public int getUsuarioLogadoId(){
        return this.usuarioId;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        visualizaPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        minhasFavoritasTituloLabel = new javax.swing.JLabel();
        anteriorButton = new javax.swing.JButton();
        proximoButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        visualizaPanel.setBackground(new java.awt.Color(163, 187, 229));
        visualizaPanel.setLayout(new java.awt.GridBagLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        visualizaPanel.add(jSeparator1, gridBagConstraints);

        minhasFavoritasTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        minhasFavoritasTituloLabel.setText("Minhas favoritas");
        minhasFavoritasTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        visualizaPanel.add(minhasFavoritasTituloLabel, gridBagConstraints);

        anteriorButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton.setText("Anterior");
        anteriorButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        visualizaPanel.add(anteriorButton, gridBagConstraints);

        proximoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton.setText("Próximo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        visualizaPanel.add(proximoButton, gridBagConstraints);

        jScrollPane1.setViewportView(visualizaPanel);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel minhasFavoritasTituloLabel;
    private javax.swing.JButton proximoButton;
    public javax.swing.JPanel visualizaPanel;
    // End of variables declaration//GEN-END:variables
}
