package com.mycompany.easytrip.telas.hospedagem;

public class TelaFavoritasHospede extends javax.swing.JPanel {

    public TelaFavoritasHospede() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        minhasFavoritasTituloLabel = new javax.swing.JLabel();
        anteriorButton = new javax.swing.JButton();
        proximoButton = new javax.swing.JButton();
        hospedagemVisualizacaoPanel1 = new com.mycompany.easytrip.telas.componentes.HospedagemVisualizacaoPanel();
        hospedagemVisualizacaoPanel2 = new com.mycompany.easytrip.telas.componentes.HospedagemVisualizacaoPanel();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(163, 187, 229));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel3.add(jSeparator1, gridBagConstraints);

        minhasFavoritasTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        minhasFavoritasTituloLabel.setText("Minhas favoritas");
        minhasFavoritasTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        jPanel3.add(minhasFavoritasTituloLabel, gridBagConstraints);

        anteriorButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton.setText("Anterior");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        jPanel3.add(anteriorButton, gridBagConstraints);

        proximoButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton.setText("Próximo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        jPanel3.add(proximoButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        jPanel3.add(hospedagemVisualizacaoPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        jPanel3.add(hospedagemVisualizacaoPanel2, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel3);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorButton;
    private com.mycompany.easytrip.telas.componentes.HospedagemVisualizacaoPanel hospedagemVisualizacaoPanel1;
    private com.mycompany.easytrip.telas.componentes.HospedagemVisualizacaoPanel hospedagemVisualizacaoPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel minhasFavoritasTituloLabel;
    private javax.swing.JButton proximoButton;
    // End of variables declaration//GEN-END:variables
}
