package com.mycompany.easytrip.telas.hospedagem;

import com.mycompany.easytrip.telas.TelaPrincipal;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

public class TelaDeGerenciamentoHospedagem extends javax.swing.JPanel {

    private int hospedagemId;
   
    public TelaDeGerenciamentoHospedagem() {
        initComponents();
    }
    
    public TelaDeGerenciamentoHospedagem(int hospedagemId){
        this();
        this.hospedagemId = hospedagemId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        informacoesPanel = new javax.swing.JPanel();
        informacoesTituloLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        descricaoLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        capacidadeMaximaLabel = new javax.swing.JLabel();
        precoDiariaLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        checkInLabel = new javax.swing.JLabel();
        checkOutLabel = new javax.swing.JLabel();
        tipoField = new javax.swing.JTextField();
        capacidadeMaximaField = new javax.swing.JTextField();
        precoDiariaField = new javax.swing.JTextField();
        atualizarButton1 = new javax.swing.JButton();
        proximoButton1 = new javax.swing.JButton();
        checkInField = new javax.swing.JTextField();
        checkOutField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        voltarButton1 = new javax.swing.JButton();
        enderecoPanel = new javax.swing.JPanel();
        cepLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        ruaLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        complementoLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        enderecoTituloLabel = new javax.swing.JLabel();
        cepField = new javax.swing.JTextField();
        numeroField = new javax.swing.JTextField();
        ruaField = new javax.swing.JTextField();
        bairroField = new javax.swing.JTextField();
        complementoField = new javax.swing.JTextField();
        cidadeField = new javax.swing.JTextField();
        estadoField = new javax.swing.JTextField();
        atualizarButton2 = new javax.swing.JButton();
        anteriorButton1 = new javax.swing.JButton();
        proximoButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        voltarButton2 = new javax.swing.JButton();
        imagemPanel = new javax.swing.JPanel();
        imagemTituloLabel = new javax.swing.JLabel();
        imagensPanel = new javax.swing.JPanel();
        removerImagemButton = new javax.swing.JButton();
        adicionarImagemButton = new javax.swing.JButton();
        anteriorButton2 = new javax.swing.JButton();
        proximoButton3 = new javax.swing.JButton();
        escolherImagemComboBox = new javax.swing.JComboBox<>();
        atualizarButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        voltarButton3 = new javax.swing.JButton();
        disponibilidadePanel = new javax.swing.JPanel();
        disponibilidadeTituloLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datasTable = new javax.swing.JTable();
        disponibilidadeDateChooser = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        anteriorButton3 = new javax.swing.JButton();
        atualizarButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        voltarButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.CardLayout());

        informacoesPanel.setBackground(new java.awt.Color(163, 187, 229));
        informacoesPanel.setLayout(new java.awt.GridBagLayout());

        informacoesTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        informacoesTituloLabel.setText("Informações");
        informacoesTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(informacoesTituloLabel, gridBagConstraints);

        tituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tituloLabel.setLabelFor(tituloField);
        tituloLabel.setText("Titulo:");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tituloLabel, gridBagConstraints);
        tituloLabel.getAccessibleContext().setAccessibleName("tituloLabel");

        tituloField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tituloField, gridBagConstraints);

        descricaoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        descricaoLabel.setLabelFor(descricaoTextArea);
        descricaoLabel.setText("Descrição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(descricaoLabel, gridBagConstraints);

        tipoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tipoLabel.setLabelFor(tipoField);
        tipoLabel.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tipoLabel, gridBagConstraints);

        capacidadeMaximaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        capacidadeMaximaLabel.setLabelFor(capacidadeMaximaField);
        capacidadeMaximaLabel.setText("Capacidade Máxima:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(capacidadeMaximaLabel, gridBagConstraints);

        precoDiariaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        precoDiariaLabel.setLabelFor(precoDiariaField);
        precoDiariaLabel.setText("Preço Diária:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(precoDiariaLabel, gridBagConstraints);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N

        descricaoTextArea.setColumns(20);
        descricaoTextArea.setRows(5);
        jScrollPane3.setViewportView(descricaoTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 5);
        informacoesPanel.add(jScrollPane3, gridBagConstraints);

        checkInLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        checkInLabel.setLabelFor(checkInField);
        checkInLabel.setText("CheckIn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkInLabel, gridBagConstraints);

        checkOutLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        checkOutLabel.setLabelFor(checkOutField);
        checkOutLabel.setText("CheckOut:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkOutLabel, gridBagConstraints);

        tipoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tipoField, gridBagConstraints);

        capacidadeMaximaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(capacidadeMaximaField, gridBagConstraints);

        precoDiariaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(precoDiariaField, gridBagConstraints);

        atualizarButton1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        atualizarButton1.setText("Atualizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(atualizarButton1, gridBagConstraints);

        proximoButton1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton1.setText("Próximo");
        proximoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(proximoButton1, gridBagConstraints);

        checkInField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkInField, gridBagConstraints);

        checkOutField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkOutField, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        informacoesPanel.add(jSeparator1, gridBagConstraints);

        voltarButton1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        voltarButton1.setText("Voltar");
        voltarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(voltarButton1, gridBagConstraints);

        add(informacoesPanel, "card2");

        enderecoPanel.setBackground(new java.awt.Color(163, 187, 229));
        enderecoPanel.setLayout(new java.awt.GridBagLayout());

        cepLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cepLabel.setLabelFor(cepField);
        cepLabel.setText("Cep:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cepLabel, gridBagConstraints);

        numeroLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        numeroLabel.setLabelFor(numeroField);
        numeroLabel.setText("Numero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(numeroLabel, gridBagConstraints);

        ruaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        ruaLabel.setLabelFor(ruaField);
        ruaLabel.setText("Rua:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(ruaLabel, gridBagConstraints);

        bairroLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        bairroLabel.setLabelFor(bairroField);
        bairroLabel.setText("Bairro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(bairroLabel, gridBagConstraints);

        complementoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        complementoLabel.setLabelFor(complementoField);
        complementoLabel.setText("Complemento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(complementoLabel, gridBagConstraints);

        cidadeLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cidadeLabel.setLabelFor(cidadeField);
        cidadeLabel.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cidadeLabel, gridBagConstraints);

        estadoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        estadoLabel.setLabelFor(estadoField);
        estadoLabel.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(estadoLabel, gridBagConstraints);

        enderecoTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        enderecoTituloLabel.setText("Endereço");
        enderecoTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(enderecoTituloLabel, gridBagConstraints);

        cepField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cepField, gridBagConstraints);

        numeroField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(numeroField, gridBagConstraints);

        ruaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(ruaField, gridBagConstraints);

        bairroField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(bairroField, gridBagConstraints);

        complementoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(complementoField, gridBagConstraints);

        cidadeField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cidadeField, gridBagConstraints);

        estadoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(estadoField, gridBagConstraints);

        atualizarButton2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        atualizarButton2.setText("Atualizar");
        atualizarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(atualizarButton2, gridBagConstraints);

        anteriorButton1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton1.setText("Anterior");
        anteriorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(anteriorButton1, gridBagConstraints);

        proximoButton2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton2.setText("Próximo");
        proximoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(proximoButton2, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        enderecoPanel.add(jSeparator2, gridBagConstraints);

        voltarButton2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        voltarButton2.setText("Voltar");
        voltarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(voltarButton2, gridBagConstraints);

        add(enderecoPanel, "card5");

        imagemPanel.setBackground(new java.awt.Color(163, 187, 229));
        imagemPanel.setLayout(new java.awt.GridBagLayout());

        imagemTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        imagemTituloLabel.setText("Imagens");
        imagemTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(imagemTituloLabel, gridBagConstraints);

        javax.swing.GroupLayout imagensPanelLayout = new javax.swing.GroupLayout(imagensPanel);
        imagensPanel.setLayout(imagensPanelLayout);
        imagensPanelLayout.setHorizontalGroup(
            imagensPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagensPanelLayout.setVerticalGroup(
            imagensPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(imagensPanel, gridBagConstraints);

        removerImagemButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        removerImagemButton.setText("remover");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(removerImagemButton, gridBagConstraints);

        adicionarImagemButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        adicionarImagemButton.setText("adicionar nova");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(adicionarImagemButton, gridBagConstraints);

        anteriorButton2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton2.setText("Anterior");
        anteriorButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(anteriorButton2, gridBagConstraints);

        proximoButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton3.setText("Próximo");
        proximoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(proximoButton3, gridBagConstraints);

        escolherImagemComboBox.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        escolherImagemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(escolherImagemComboBox, gridBagConstraints);

        atualizarButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        atualizarButton3.setLabel("Atualizar");
        atualizarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(atualizarButton3, gridBagConstraints);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        imagemPanel.add(jSeparator3, gridBagConstraints);

        voltarButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        voltarButton3.setText("Voltar");
        voltarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(voltarButton3, gridBagConstraints);

        add(imagemPanel, "card5");

        disponibilidadePanel.setBackground(new java.awt.Color(163, 187, 229));
        disponibilidadePanel.setLayout(new java.awt.GridBagLayout());

        disponibilidadeTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        disponibilidadeTituloLabel.setText("Disponibilidades");
        disponibilidadeTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(disponibilidadeTituloLabel, gridBagConstraints);

        datasTable.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        datasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"24/04/2025", "Disponivel"},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Data", "Status"
            }
        ));
        datasTable.setMinimumSize(new java.awt.Dimension(50, 120));
        jScrollPane1.setViewportView(datasTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(jScrollPane1, gridBagConstraints);

        disponibilidadeDateChooser.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(disponibilidadeDateChooser, gridBagConstraints);

        jButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        jButton3.setText("adicionar data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(jButton3, gridBagConstraints);

        anteriorButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton3.setText("Anterior");
        anteriorButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(anteriorButton3, gridBagConstraints);

        atualizarButton4.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        atualizarButton4.setText("Atualizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(atualizarButton4, gridBagConstraints);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        disponibilidadePanel.add(jSeparator4, gridBagConstraints);

        voltarButton4.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        voltarButton4.setText("Voltar");
        voltarButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(voltarButton4, gridBagConstraints);

        add(disponibilidadePanel, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarButton2ActionPerformed

    private void proximoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButton1ActionPerformed
        // TODO add your handling code here:
        proximoCardLayout();
    }//GEN-LAST:event_proximoButton1ActionPerformed

    private void proximoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButton2ActionPerformed
        // TODO add your handling code here:
        proximoCardLayout();
    }//GEN-LAST:event_proximoButton2ActionPerformed

    private void anteriorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButton1ActionPerformed
        // TODO add your handling code here:
        anteriorCardLayout();
    }//GEN-LAST:event_anteriorButton1ActionPerformed

    private void proximoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButton3ActionPerformed
        // TODO add your handling code here:
        proximoCardLayout();
    }//GEN-LAST:event_proximoButton3ActionPerformed

    private void anteriorButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButton2ActionPerformed
        // TODO add your handling code here:
        anteriorCardLayout();
    }//GEN-LAST:event_anteriorButton2ActionPerformed

    private void atualizarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarButton3ActionPerformed

    private void anteriorButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButton3ActionPerformed
        // TODO add your handling code here:
        anteriorCardLayout();
    }//GEN-LAST:event_anteriorButton3ActionPerformed

    private void voltarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton1ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton1ActionPerformed

    private void voltarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton2ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton2ActionPerformed

    private void voltarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton3ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton3ActionPerformed

    private void voltarButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton4ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton4ActionPerformed

    private void voltarPagina(){
        TelaPrincipal telaPrincipal = (TelaPrincipal)SwingUtilities.getWindowAncestor(this);
        telaPrincipal.voltarPagina();
    }

    private void proximoCardLayout(){
        CardLayout layout = (CardLayout) this.getLayout();
        layout.next(this);
    }
    
    private void anteriorCardLayout(){
        CardLayout layout = (CardLayout) this.getLayout();
        layout.previous(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarImagemButton;
    private javax.swing.JButton anteriorButton1;
    private javax.swing.JButton anteriorButton2;
    private javax.swing.JButton anteriorButton3;
    private javax.swing.JButton atualizarButton1;
    private javax.swing.JButton atualizarButton2;
    private javax.swing.JButton atualizarButton3;
    private javax.swing.JButton atualizarButton4;
    private javax.swing.JTextField bairroField;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField capacidadeMaximaField;
    private javax.swing.JLabel capacidadeMaximaLabel;
    private javax.swing.JTextField cepField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JTextField checkInField;
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JTextField checkOutField;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JTextField cidadeField;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField complementoField;
    private javax.swing.JLabel complementoLabel;
    private javax.swing.JTable datasTable;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextArea descricaoTextArea;
    private com.toedter.calendar.JDateChooser disponibilidadeDateChooser;
    private javax.swing.JPanel disponibilidadePanel;
    private javax.swing.JLabel disponibilidadeTituloLabel;
    private javax.swing.JPanel enderecoPanel;
    private javax.swing.JLabel enderecoTituloLabel;
    private javax.swing.JComboBox<String> escolherImagemComboBox;
    private javax.swing.JTextField estadoField;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JPanel imagemPanel;
    private javax.swing.JLabel imagemTituloLabel;
    private javax.swing.JPanel imagensPanel;
    private javax.swing.JPanel informacoesPanel;
    private javax.swing.JLabel informacoesTituloLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField numeroField;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField precoDiariaField;
    private javax.swing.JLabel precoDiariaLabel;
    private javax.swing.JButton proximoButton1;
    private javax.swing.JButton proximoButton2;
    private javax.swing.JButton proximoButton3;
    private javax.swing.JButton removerImagemButton;
    private javax.swing.JTextField ruaField;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JTextField tipoField;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tituloField;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton voltarButton1;
    private javax.swing.JButton voltarButton2;
    private javax.swing.JButton voltarButton3;
    private javax.swing.JButton voltarButton4;
    // End of variables declaration//GEN-END:variables
}
