package com.mycompany.easytrip.telas.hospedagem;

import com.mycompany.easytrip.controllers.GerenciarHospedagemController;
import com.mycompany.easytrip.dominio.enums.EstadoBrasil;
import com.mycompany.easytrip.dominio.enums.TipoDeHospedagem;
import com.mycompany.easytrip.telas.TelaPrincipal;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;

public class TelaDeGerenciamentoHospedagem extends javax.swing.JPanel {

    private int hospedagemId;
    private GerenciarHospedagemController controller;
   
    public TelaDeGerenciamentoHospedagem() {
        initComponents();
    }
    
    public TelaDeGerenciamentoHospedagem(int hospedagemId){
        this();
        this.hospedagemId = hospedagemId;
        this.controller = new GerenciarHospedagemController(this);
        controller.carregarHospedagem(hospedagemId);
    }
    
    public int getMesSelecionado(){
        return escolheMes.getMonth() + 1;
    }
    
    public int getAnoSelecionado(){
        return escolheAno.getYear();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        informacoesPanel = new javax.swing.JPanel();
        informacoesTituloLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        descricaoLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        capacidadeMaximaLabel = new javax.swing.JLabel();
        precoDiariaLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        checkInLabel = new javax.swing.JLabel();
        checkOutLabel = new javax.swing.JLabel();
        atualizarButton1 = new javax.swing.JButton();
        proximoButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        voltarButton5 = new com.mycompany.easytrip.telas.componentes.VoltarButton();
        precoDiariaField1 = new javax.swing.JFormattedTextField();
        checkOutField1 = new javax.swing.JFormattedTextField();
        checkInField1 = new javax.swing.JFormattedTextField();
        capacidadeMaximaField1 = new javax.swing.JFormattedTextField();
        tipoHospedagemComboBox = new javax.swing.JComboBox<>();
        enderecoPanel = new javax.swing.JPanel();
        cepLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        ruaLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        complementoLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        enderecoTituloLabel = new javax.swing.JLabel();
        cepField = new javax.swing.JTextField();
        numeroField = new javax.swing.JTextField();
        ruaField = new javax.swing.JTextField();
        bairroField = new javax.swing.JTextField();
        complementoField = new javax.swing.JTextField();
        cidadeField = new javax.swing.JTextField();
        anteriorButton1 = new javax.swing.JButton();
        proximoButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        voltarButton2 = new javax.swing.JButton();
        estadoComboBox = new javax.swing.JComboBox<>();
        imagemPanel = new javax.swing.JPanel();
        imagemTituloLabel = new javax.swing.JLabel();
        removerImagemButton = new javax.swing.JButton();
        adicionarImagemButton = new javax.swing.JButton();
        anteriorButton2 = new javax.swing.JButton();
        proximoButton3 = new javax.swing.JButton();
        escolherImagemComboBox = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        voltarButton3 = new javax.swing.JButton();
        imagemPanel1 = new com.mycompany.easytrip.telas.componentes.ImagemPanel();
        disponibilidadePanel = new javax.swing.JPanel();
        disponibilidadeTituloLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        disponibilidadesTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        anteriorButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        voltarButton4 = new javax.swing.JButton();
        removerDisponibilidadeButton = new javax.swing.JButton();
        escolheMes = new com.toedter.calendar.JMonthChooser();
        escolheAno = new com.toedter.calendar.JYearChooser();

        setBackground(new java.awt.Color(163, 187, 229));
        setLayout(new java.awt.CardLayout());

        informacoesPanel.setBackground(new java.awt.Color(163, 187, 229));
        informacoesPanel.setLayout(new java.awt.GridBagLayout());

        informacoesTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        informacoesTituloLabel.setText("Informações");
        informacoesTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(informacoesTituloLabel, gridBagConstraints);

        tituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tituloLabel.setLabelFor(tituloField);
        tituloLabel.setText("Titulo:");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tituloLabel, gridBagConstraints);
        tituloLabel.getAccessibleContext().setAccessibleName("tituloLabel");

        tituloField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tituloField, gridBagConstraints);

        descricaoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        descricaoLabel.setLabelFor(descricaoTextArea);
        descricaoLabel.setText("Descrição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(descricaoLabel, gridBagConstraints);

        tipoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        tipoLabel.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tipoLabel, gridBagConstraints);

        capacidadeMaximaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        capacidadeMaximaLabel.setText("Capacidade Máxima:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(capacidadeMaximaLabel, gridBagConstraints);

        precoDiariaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        precoDiariaLabel.setText("Preço Diária:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(precoDiariaLabel, gridBagConstraints);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N

        descricaoTextArea.setColumns(20);
        descricaoTextArea.setRows(5);
        jScrollPane3.setViewportView(descricaoTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 5);
        informacoesPanel.add(jScrollPane3, gridBagConstraints);

        checkInLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        checkInLabel.setText("CheckIn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkInLabel, gridBagConstraints);

        checkOutLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        checkOutLabel.setText("CheckOut:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkOutLabel, gridBagConstraints);

        atualizarButton1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        atualizarButton1.setText("Atualizar");
        atualizarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(atualizarButton1, gridBagConstraints);

        proximoButton1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton1.setText("Próximo");
        proximoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(proximoButton1, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        informacoesPanel.add(jSeparator1, gridBagConstraints);

        voltarButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(voltarButton5, gridBagConstraints);

        precoDiariaField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        precoDiariaField1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(precoDiariaField1, gridBagConstraints);

        checkOutField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        checkOutField1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkOutField1, gridBagConstraints);

        checkInField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        checkInField1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(checkInField1, gridBagConstraints);

        capacidadeMaximaField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        capacidadeMaximaField1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(capacidadeMaximaField1, gridBagConstraints);

        tipoHospedagemComboBox.setModel(new DefaultComboBoxModel<>(TipoDeHospedagem.values()));
        tipoHospedagemComboBox.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        informacoesPanel.add(tipoHospedagemComboBox, gridBagConstraints);

        add(informacoesPanel, "card2");

        enderecoPanel.setBackground(new java.awt.Color(163, 187, 229));
        enderecoPanel.setLayout(new java.awt.GridBagLayout());

        cepLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cepLabel.setLabelFor(cepField);
        cepLabel.setText("Cep:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cepLabel, gridBagConstraints);

        numeroLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        numeroLabel.setLabelFor(numeroField);
        numeroLabel.setText("Numero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(numeroLabel, gridBagConstraints);

        ruaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        ruaLabel.setLabelFor(ruaField);
        ruaLabel.setText("Rua:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(ruaLabel, gridBagConstraints);

        bairroLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        bairroLabel.setLabelFor(bairroField);
        bairroLabel.setText("Bairro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(bairroLabel, gridBagConstraints);

        complementoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        complementoLabel.setLabelFor(complementoField);
        complementoLabel.setText("Complemento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(complementoLabel, gridBagConstraints);

        cidadeLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cidadeLabel.setLabelFor(cidadeField);
        cidadeLabel.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cidadeLabel, gridBagConstraints);

        estadoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        estadoLabel.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(estadoLabel, gridBagConstraints);

        enderecoTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        enderecoTituloLabel.setText("Endereço");
        enderecoTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(enderecoTituloLabel, gridBagConstraints);

        cepField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cepField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cepField, gridBagConstraints);

        numeroField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        numeroField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(numeroField, gridBagConstraints);

        ruaField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        ruaField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(ruaField, gridBagConstraints);

        bairroField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        bairroField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(bairroField, gridBagConstraints);

        complementoField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        complementoField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(complementoField, gridBagConstraints);

        cidadeField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cidadeField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(cidadeField, gridBagConstraints);

        anteriorButton1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton1.setText("Anterior");
        anteriorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(anteriorButton1, gridBagConstraints);

        proximoButton2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton2.setText("Próximo");
        proximoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(proximoButton2, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        enderecoPanel.add(jSeparator2, gridBagConstraints);

        voltarButton2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        voltarButton2.setText("Voltar");
        voltarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(voltarButton2, gridBagConstraints);

        estadoComboBox.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        estadoComboBox.setModel(new DefaultComboBoxModel<>(EstadoBrasil.values()));
        estadoComboBox.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        enderecoPanel.add(estadoComboBox, gridBagConstraints);

        add(enderecoPanel, "card5");

        imagemPanel.setBackground(new java.awt.Color(163, 187, 229));
        imagemPanel.setLayout(new java.awt.GridBagLayout());

        imagemTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        imagemTituloLabel.setText("Imagens");
        imagemTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(imagemTituloLabel, gridBagConstraints);

        removerImagemButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        removerImagemButton.setText("Remover");
        removerImagemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerImagemButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(removerImagemButton, gridBagConstraints);

        adicionarImagemButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        adicionarImagemButton.setText("Adicionar");
        adicionarImagemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarImagemButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(adicionarImagemButton, gridBagConstraints);

        anteriorButton2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton2.setText("Anterior");
        anteriorButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 10, 10);
        imagemPanel.add(anteriorButton2, gridBagConstraints);

        proximoButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        proximoButton3.setText("Próximo");
        proximoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 10, 10);
        imagemPanel.add(proximoButton3, gridBagConstraints);

        escolherImagemComboBox.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        escolherImagemComboBox.setModel(new DefaultComboBoxModel<>());
        escolherImagemComboBox.setEnabled(false);
        escolherImagemComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                escolherImagemComboBoxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(escolherImagemComboBox, gridBagConstraints);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        imagemPanel.add(jSeparator3, gridBagConstraints);

        voltarButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        voltarButton3.setText("Voltar");
        voltarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 10, 10);
        imagemPanel.add(voltarButton3, gridBagConstraints);

        imagemPanel1.setBackground(new java.awt.Color(255, 255, 255));
        imagemPanel1.setPreferredSize(new java.awt.Dimension(300, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 300;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        imagemPanel.add(imagemPanel1, gridBagConstraints);

        add(imagemPanel, "card5");

        disponibilidadePanel.setBackground(new java.awt.Color(163, 187, 229));
        disponibilidadePanel.setLayout(new java.awt.GridBagLayout());

        disponibilidadeTituloLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        disponibilidadeTituloLabel.setText("Disponibilidades");
        disponibilidadeTituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(disponibilidadeTituloLabel, gridBagConstraints);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N

        disponibilidadesTable.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        disponibilidadesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Status"
            }
        ));
        disponibilidadesTable.setMinimumSize(new java.awt.Dimension(50, 120));
        disponibilidadesTable.setPreferredSize(new java.awt.Dimension(100, 300));
        disponibilidadesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        disponibilidadesTable.setShowGrid(false);
        jScrollPane1.setViewportView(disponibilidadesTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(jScrollPane1, gridBagConstraints);

        jButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(jButton3, gridBagConstraints);

        anteriorButton3.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        anteriorButton3.setText("Anterior");
        anteriorButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(anteriorButton3, gridBagConstraints);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        disponibilidadePanel.add(jSeparator4, gridBagConstraints);

        voltarButton4.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        voltarButton4.setText("Voltar");
        voltarButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 5, 10);
        disponibilidadePanel.add(voltarButton4, gridBagConstraints);

        removerDisponibilidadeButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        removerDisponibilidadeButton.setText("Remover");
        removerDisponibilidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerDisponibilidadeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(removerDisponibilidadeButton, gridBagConstraints);

        escolheMes.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        escolheMes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                escolheMesPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(escolheMes, gridBagConstraints);

        escolheAno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                escolheAnoPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 10);
        disponibilidadePanel.add(escolheAno, gridBagConstraints);

        add(disponibilidadePanel, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void proximoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButton1ActionPerformed
        // TODO add your handling code here:
        proximoCardLayout();
    }//GEN-LAST:event_proximoButton1ActionPerformed

    private void proximoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButton2ActionPerformed
        // TODO add your handling code here:
        proximoCardLayout();
    }//GEN-LAST:event_proximoButton2ActionPerformed

    private void anteriorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButton1ActionPerformed
        // TODO add your handling code here:
        anteriorCardLayout();
    }//GEN-LAST:event_anteriorButton1ActionPerformed

    private void proximoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButton3ActionPerformed
        // TODO add your handling code here:
        proximoCardLayout();
    }//GEN-LAST:event_proximoButton3ActionPerformed

    private void anteriorButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButton2ActionPerformed
        // TODO add your handling code here:
        anteriorCardLayout();
    }//GEN-LAST:event_anteriorButton2ActionPerformed

    private void anteriorButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButton3ActionPerformed
        // TODO add your handling code here:
        anteriorCardLayout();
    }//GEN-LAST:event_anteriorButton3ActionPerformed

    private void voltarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton2ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton2ActionPerformed

    private void voltarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton3ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton3ActionPerformed

    private void voltarButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton4ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton4ActionPerformed

    private void adicionarImagemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarImagemButtonActionPerformed
        // TODO add your handling code here:
        controller.adicionarImagem();
    }//GEN-LAST:event_adicionarImagemButtonActionPerformed

    private void removerImagemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerImagemButtonActionPerformed
        // TODO add your handling code here:
        controller.removerImagem();
    }//GEN-LAST:event_removerImagemButtonActionPerformed

    private void escolherImagemComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_escolherImagemComboBoxItemStateChanged
        // TODO add your handling code here:
        controller.mudarImagemDaTela();
    }//GEN-LAST:event_escolherImagemComboBoxItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        controller.adicionarDisponibilidade();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void escolheMesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_escolheMesPropertyChange
        // TODO add your handling code here:
        controller.preencherDisponibilidadeTable();
    }//GEN-LAST:event_escolheMesPropertyChange

    private void escolheAnoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_escolheAnoPropertyChange
        // TODO add your handling code here:
        controller.preencherDisponibilidadeTable();
    }//GEN-LAST:event_escolheAnoPropertyChange

    private void removerDisponibilidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerDisponibilidadeButtonActionPerformed
        // TODO add your handling code here:
        controller.removerDisponibilidade();
    }//GEN-LAST:event_removerDisponibilidadeButtonActionPerformed

    private void atualizarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButton1ActionPerformed
        // TODO add your handling code here:
        controller.atualizarInformacoes();
    }//GEN-LAST:event_atualizarButton1ActionPerformed

    private void voltarButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton5ActionPerformed
        // TODO add your handling code here:
        voltarPagina();
    }//GEN-LAST:event_voltarButton5ActionPerformed

    
    private void voltarPagina(){
        TelaPrincipal telaPrincipal = (TelaPrincipal)SwingUtilities.getWindowAncestor(this);
        telaPrincipal.mudarParaTelaHospedagensCadastradas();
    }

    private void proximoCardLayout(){
        CardLayout layout = (CardLayout) this.getLayout();
        layout.next(this);
    }
    
    private void anteriorCardLayout(){
        CardLayout layout = (CardLayout) this.getLayout();
        layout.previous(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarImagemButton;
    private javax.swing.JButton anteriorButton1;
    private javax.swing.JButton anteriorButton2;
    private javax.swing.JButton anteriorButton3;
    private javax.swing.JButton atualizarButton1;
    public javax.swing.JTextField bairroField;
    private javax.swing.JLabel bairroLabel;
    public javax.swing.JFormattedTextField capacidadeMaximaField1;
    private javax.swing.JLabel capacidadeMaximaLabel;
    public javax.swing.JTextField cepField;
    private javax.swing.JLabel cepLabel;
    public javax.swing.JFormattedTextField checkInField1;
    private javax.swing.JLabel checkInLabel;
    public javax.swing.JFormattedTextField checkOutField1;
    private javax.swing.JLabel checkOutLabel;
    public javax.swing.JTextField cidadeField;
    private javax.swing.JLabel cidadeLabel;
    public javax.swing.JTextField complementoField;
    private javax.swing.JLabel complementoLabel;
    private javax.swing.JLabel descricaoLabel;
    public javax.swing.JTextArea descricaoTextArea;
    public javax.swing.JPanel disponibilidadePanel;
    private javax.swing.JLabel disponibilidadeTituloLabel;
    public javax.swing.JTable disponibilidadesTable;
    private javax.swing.JPanel enderecoPanel;
    private javax.swing.JLabel enderecoTituloLabel;
    private com.toedter.calendar.JYearChooser escolheAno;
    private com.toedter.calendar.JMonthChooser escolheMes;
    public javax.swing.JComboBox<Integer> escolherImagemComboBox;
    public javax.swing.JComboBox<EstadoBrasil> estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JPanel imagemPanel;
    public com.mycompany.easytrip.telas.componentes.ImagemPanel imagemPanel1;
    private javax.swing.JLabel imagemTituloLabel;
    private javax.swing.JPanel informacoesPanel;
    private javax.swing.JLabel informacoesTituloLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField numeroField;
    private javax.swing.JLabel numeroLabel;
    public javax.swing.JFormattedTextField precoDiariaField1;
    private javax.swing.JLabel precoDiariaLabel;
    private javax.swing.JButton proximoButton1;
    private javax.swing.JButton proximoButton2;
    private javax.swing.JButton proximoButton3;
    private javax.swing.JButton removerDisponibilidadeButton;
    private javax.swing.JButton removerImagemButton;
    public javax.swing.JTextField ruaField;
    private javax.swing.JLabel ruaLabel;
    public javax.swing.JComboBox<TipoDeHospedagem> tipoHospedagemComboBox;
    private javax.swing.JLabel tipoLabel;
    public javax.swing.JTextField tituloField;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton voltarButton2;
    private javax.swing.JButton voltarButton3;
    private javax.swing.JButton voltarButton4;
    private com.mycompany.easytrip.telas.componentes.VoltarButton voltarButton5;
    // End of variables declaration//GEN-END:variables
}
