package com.mycompany.easytrip.telas;

import com.mycompany.easytrip.dominio.entidades.Usuario;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

public class TelaContaDoUsuario extends javax.swing.JPanel {

    private Usuario usuario;
    
    public TelaContaDoUsuario() {
        initComponents();
    }
    
    public TelaContaDoUsuario(Usuario usuario){
        initComponents();
        
        this.usuario = usuario;
        preencherCampos();
    }
    
    private void preencherCampos(){
        nomeField.setText(usuario.getNome());
        emailField.setText(usuario.getEnderecoEmail());
        
        LocalDate dataNascimento = usuario.getDataNascimento();
        dataNascimentoChooser.setDate(Date.from(dataNascimento.atStartOfDay(ZoneId.systemDefault()).toInstant()));
        cpfField.setText(usuario.getValorCpf());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        minhaContaLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        dataDeNascimentoLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        cpfField = new javax.swing.JTextField();
        dataNascimentoChooser = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(163, 187, 229));
        setMinimumSize(new java.awt.Dimension(534, 330));
        setLayout(new java.awt.GridBagLayout());

        minhaContaLabel.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        minhaContaLabel.setText("Minha conta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(minhaContaLabel, gridBagConstraints);

        nomeLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        nomeLabel.setLabelFor(nomeField);
        nomeLabel.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(nomeLabel, gridBagConstraints);

        nomeField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        nomeField.setEnabled(false);
        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(nomeField, gridBagConstraints);

        emailLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        emailLabel.setLabelFor(emailField);
        emailLabel.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(emailLabel, gridBagConstraints);

        emailField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        emailField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(emailField, gridBagConstraints);

        dataDeNascimentoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataDeNascimentoLabel.setLabelFor(dataNascimentoChooser);
        dataDeNascimentoLabel.setText("Data de Nascimento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(dataDeNascimentoLabel, gridBagConstraints);

        cpfLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cpfLabel.setLabelFor(cpfField);
        cpfLabel.setText("CPF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(cpfLabel, gridBagConstraints);

        cpfField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(cpfField, gridBagConstraints);

        dataNascimentoChooser.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(dataNascimentoChooser, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(jSeparator1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel dataDeNascimentoLabel;
    private com.toedter.calendar.JDateChooser dataNascimentoChooser;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel minhaContaLabel;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    // End of variables declaration//GEN-END:variables
}
