package com.mycompany.easytrip.telas;

import com.mycompany.easytrip.controllers.LoginController;
import java.awt.*;
import java.util.Date;
import javax.swing.SwingUtilities;
public class TelaDeLogin extends javax.swing.JPanel {

    private final LoginController controller;
    
    public TelaDeLogin() {
        initComponents();
        this.controller = new LoginController(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logoLabel = new javax.swing.JLabel();
        lateralPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        senhaLabel1 = new javax.swing.JLabel();
        senhaField1 = new javax.swing.JPasswordField();
        registrarButton = new javax.swing.JButton();
        entrarButton = new javax.swing.JButton();
        registrarPanel = new javax.swing.JPanel();
        registrarLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfField = new javax.swing.JTextField();
        senhaLabel2 = new javax.swing.JLabel();
        emailField2 = new javax.swing.JTextField();
        emailLabel2 = new javax.swing.JLabel();
        senhaField2 = new javax.swing.JPasswordField();
        concluirButton = new javax.swing.JButton();
        dataNascimentoDateChosser = new com.toedter.calendar.JDateChooser();
        dataNascimentoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(213, 181, 156));
        setLayout(new java.awt.GridLayout(1, 1));

        logoLabel.setBackground(new java.awt.Color(213, 181, 156));
        logoLabel.setFont(new java.awt.Font("Arial", 1, 54)); // NOI18N
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capivaraicon.png"))); // NOI18N
        logoLabel.setText("EasyTrip");
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoLabel.setPreferredSize(new java.awt.Dimension(120, 80));
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(logoLabel);

        lateralPanel.setBackground(new java.awt.Color(213, 181, 156));
        lateralPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(85, 116, 132));
        loginPanel.setLayout(new java.awt.GridBagLayout());

        loginLabel.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        loginLabel.setText("Login");
        loginLabel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        loginPanel.add(loginLabel, gridBagConstraints);

        emailLabel1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        emailLabel1.setLabelFor(emailTextField1);
        emailLabel1.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        loginPanel.add(emailLabel1, gridBagConstraints);

        emailTextField1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        emailTextField1.setMargin(new java.awt.Insets(2, 10, 2, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        loginPanel.add(emailTextField1, gridBagConstraints);

        senhaLabel1.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        senhaLabel1.setLabelFor(senhaField1);
        senhaLabel1.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        loginPanel.add(senhaLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        loginPanel.add(senhaField1, gridBagConstraints);

        registrarButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        registrarButton.setText("Registra-se");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 20, 5);
        loginPanel.add(registrarButton, gridBagConstraints);

        entrarButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        entrarButton.setText("Entrar");
        entrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 30, 5);
        loginPanel.add(entrarButton, gridBagConstraints);

        lateralPanel.add(loginPanel, "card2");

        registrarPanel.setBackground(new java.awt.Color(85, 116, 132));
        registrarPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        registrarPanel.setLayout(new java.awt.GridBagLayout());

        registrarLabel.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        registrarLabel.setText("Registrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        registrarPanel.add(registrarLabel, gridBagConstraints);

        nomeLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        nomeLabel.setLabelFor(nomeField);
        nomeLabel.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        registrarPanel.add(nomeLabel, gridBagConstraints);

        nomeField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        registrarPanel.add(nomeField, gridBagConstraints);

        cpfLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cpfLabel.setLabelFor(cpfField);
        cpfLabel.setText("CPF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        registrarPanel.add(cpfLabel, gridBagConstraints);

        cpfField.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        registrarPanel.add(cpfField, gridBagConstraints);

        senhaLabel2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        senhaLabel2.setLabelFor(senhaField2);
        senhaLabel2.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        registrarPanel.add(senhaLabel2, gridBagConstraints);

        emailField2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        registrarPanel.add(emailField2, gridBagConstraints);

        emailLabel2.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        emailLabel2.setLabelFor(emailField2);
        emailLabel2.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        registrarPanel.add(emailLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        registrarPanel.add(senhaField2, gridBagConstraints);

        concluirButton.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        concluirButton.setText("Concluir");
        concluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 5);
        registrarPanel.add(concluirButton, gridBagConstraints);

        dataNascimentoDateChosser.setDate(new Date());
        dataNascimentoDateChosser.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        registrarPanel.add(dataNascimentoDateChosser, gridBagConstraints);

        dataNascimentoLabel.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        dataNascimentoLabel.setLabelFor(dataNascimentoDateChosser);
        dataNascimentoLabel.setText("Data de Nascimento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        registrarPanel.add(dataNascimentoLabel, gridBagConstraints);

        lateralPanel.add(registrarPanel, "card3");

        add(lateralPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        // TODO add your handling code here:
        irParaRegistrar();
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void concluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirButtonActionPerformed
        // TODO add your handling code here:
        controller.registrarUsuario();
    }//GEN-LAST:event_concluirButtonActionPerformed

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
        // TODO add your handling code here:
        controller.logarUsuario();
    }//GEN-LAST:event_entrarButtonActionPerformed

    private void irParaRegistrar(){
        CardLayout cardLayout = (CardLayout) lateralPanel.getLayout();
        cardLayout.next(lateralPanel);
    }
    
    public void voltarParaLogin(){
        CardLayout cardLayout = (CardLayout) lateralPanel.getLayout();
        cardLayout.previous(lateralPanel);
        nomeField.setText("");
        cpfField.setText("");
        emailField2.setText("");
        senhaField2.setText("");
        dataNascimentoDateChosser.setDate(null);
    }
    
    public void atualizarTelaPrincipal(int usuarioId){
        TelaPrincipal telaPrincipal = (TelaPrincipal)SwingUtilities.getWindowAncestor(this);
        telaPrincipal.setUsuarioLogado(usuarioId);
        telaPrincipal.configurarEstadoMenu(true);
        telaPrincipal.mudarParaTelaVisualizacaoHospedagens();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton concluirButton;
    public javax.swing.JTextField cpfField;
    private javax.swing.JLabel cpfLabel;
    public com.toedter.calendar.JDateChooser dataNascimentoDateChosser;
    private javax.swing.JLabel dataNascimentoLabel;
    public javax.swing.JTextField emailField2;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    public javax.swing.JTextField emailTextField1;
    private javax.swing.JButton entrarButton;
    public javax.swing.JPanel lateralPanel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLabel;
    public javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton registrarButton;
    private javax.swing.JLabel registrarLabel;
    private javax.swing.JPanel registrarPanel;
    public javax.swing.JPasswordField senhaField1;
    public javax.swing.JPasswordField senhaField2;
    private javax.swing.JLabel senhaLabel1;
    private javax.swing.JLabel senhaLabel2;
    // End of variables declaration//GEN-END:variables
}
