package com.mycompany.easytrip.telas;

import com.mycompany.easytrip.dominio.entidades.Usuario;
import com.mycompany.easytrip.telas.grupos.*;
import com.mycompany.easytrip.telas.reservas.*;
import com.mycompany.easytrip.telas.hospedagem.*;

import java.awt.Component;
import javax.swing.JPanel;

public class TelaPrincipal extends javax.swing.JFrame{
    private JPanel telaAnterior;
    private Usuario usuario;
    
    public TelaPrincipal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDeLogin1 = new com.mycompany.easytrip.telas.TelaDeLogin();
        barraMenu = new javax.swing.JMenuBar();
        contaMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        minhaContaMenuItem = new javax.swing.JMenuItem();
        painelDoAnfitriãoMenu = new javax.swing.JMenu();
        hospedagensCadastradaMenuItem = new javax.swing.JMenuItem();
        reservasPendentesMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();
        hospedagemMenu = new javax.swing.JMenu();
        visualizarMenuItem = new javax.swing.JMenuItem();
        favoritasMenuItem = new javax.swing.JMenuItem();
        minhasReservasMenuItem = new javax.swing.JMenuItem();
        gruposMenu = new javax.swing.JMenu();
        verGruposMenuItem = new javax.swing.JMenuItem();
        favoritasGrupoMenuItem = new javax.swing.JMenuItem();
        rankingHospedagensMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2, 1, 1));

        telaDeLogin1.setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().add(telaDeLogin1);

        contaMenu.setText("Conta");

        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        contaMenu.add(loginMenuItem);

        minhaContaMenuItem.setText("Minha Conta");
        minhaContaMenuItem.setEnabled(false);
        minhaContaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhaContaMenuItemActionPerformed(evt);
            }
        });
        contaMenu.add(minhaContaMenuItem);

        painelDoAnfitriãoMenu.setText("Painel do anfitrião");
        painelDoAnfitriãoMenu.setEnabled(false);

        hospedagensCadastradaMenuItem.setText("Hospedagens cadastradas");
        hospedagensCadastradaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospedagensCadastradaMenuItemActionPerformed(evt);
            }
        });
        painelDoAnfitriãoMenu.add(hospedagensCadastradaMenuItem);

        reservasPendentesMenuItem.setText("Reservas pendentes");
        reservasPendentesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasPendentesMenuItemActionPerformed(evt);
            }
        });
        painelDoAnfitriãoMenu.add(reservasPendentesMenuItem);

        contaMenu.add(painelDoAnfitriãoMenu);

        sairMenuItem.setText("Sair");
        sairMenuItem.setEnabled(false);
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        contaMenu.add(sairMenuItem);

        barraMenu.add(contaMenu);

        hospedagemMenu.setText("Hospedagens");
        hospedagemMenu.setEnabled(false);

        visualizarMenuItem.setText("Visualizar");
        visualizarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarMenuItemActionPerformed(evt);
            }
        });
        hospedagemMenu.add(visualizarMenuItem);

        favoritasMenuItem.setText("Favoritas");
        favoritasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritasMenuItemActionPerformed(evt);
            }
        });
        hospedagemMenu.add(favoritasMenuItem);

        minhasReservasMenuItem.setText("Minhas reservas");
        minhasReservasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhasReservasMenuItemActionPerformed(evt);
            }
        });
        hospedagemMenu.add(minhasReservasMenuItem);

        barraMenu.add(hospedagemMenu);

        gruposMenu.setText("Grupos");
        gruposMenu.setEnabled(false);

        verGruposMenuItem.setText("Ver grupos");
        verGruposMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGruposMenuItemActionPerformed(evt);
            }
        });
        gruposMenu.add(verGruposMenuItem);

        favoritasGrupoMenuItem.setText("Hospedagens favoritas");
        favoritasGrupoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritasGrupoMenuItemActionPerformed(evt);
            }
        });
        gruposMenu.add(favoritasGrupoMenuItem);

        rankingHospedagensMenuItem.setText("Ranking das hospedagens");
        rankingHospedagensMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingHospedagensMenuItemActionPerformed(evt);
            }
        });
        gruposMenu.add(rankingHospedagensMenuItem);

        barraMenu.add(gruposMenu);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minhaContaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhaContaMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaContaDoUsuario();
    }//GEN-LAST:event_minhaContaMenuItemActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        // TODO add your handling code here:
        configurarEstadoMenu(false);
        setUsuarioLogado(null);
        mudarParaTelaDeLogin();
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaDeLogin();
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void visualizarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaVisualizacaoHospedagens();
    }//GEN-LAST:event_visualizarMenuItemActionPerformed

    private void reservasPendentesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasPendentesMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaReservasPendentes();
    }//GEN-LAST:event_reservasPendentesMenuItemActionPerformed

    private void hospedagensCadastradaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospedagensCadastradaMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaHospedagensCadastradas();
    }//GEN-LAST:event_hospedagensCadastradaMenuItemActionPerformed

    private void favoritasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoritasMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaFavoritasHospede();
    }//GEN-LAST:event_favoritasMenuItemActionPerformed

    private void minhasReservasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhasReservasMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaMinhasReservas();
    }//GEN-LAST:event_minhasReservasMenuItemActionPerformed

    private void verGruposMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGruposMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaVisualizarGrupos();
    }//GEN-LAST:event_verGruposMenuItemActionPerformed

    private void favoritasGrupoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoritasGrupoMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaFavoritasGrupo();
    }//GEN-LAST:event_favoritasGrupoMenuItemActionPerformed

    private void rankingHospedagensMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingHospedagensMenuItemActionPerformed
        // TODO add your handling code here:
        mudarParaTelaRankingGrupo();
    }//GEN-LAST:event_rankingHospedagensMenuItemActionPerformed
    
    public void setUsuarioLogado(Usuario usuario){
        this.usuario = usuario;
    }
    
    public Usuario getUsuarioLogado(Usuario usuario){
        return this.usuario;
    }
    
    private void mudarTela(JPanel tela){
        salvarPaginaAnterior();
        limparTela();
        
        this.add(tela);
        this.revalidate();
        this.repaint();
    }
    
    public void mudarParaTelaHospedagensCadastradas(){
        TelaHospedagensCadastradas tela = new TelaHospedagensCadastradas();
        mudarTela(tela);
    }
    
    public void mudarParaTelaGerenciamentoHospedagem(int hospedagemId){
        TelaDeGerenciamentoHospedagem tela = new TelaDeGerenciamentoHospedagem(hospedagemId);
        mudarTela(tela);
    }
    
    public void mudarParaTelaContaDoUsuario(){
        TelaContaDoUsuario tela = new TelaContaDoUsuario(usuario);
        mudarTela(tela);
    }
    
    public void mudarParaTelaCriarHospedagem(){
        TelaCriarHospedagem tela = new TelaCriarHospedagem();
        mudarTela(tela);
    }
    
    public void mudarParaTelaDeLogin(){
        TelaDeLogin tela = new TelaDeLogin();
        mudarTela(tela);
    }
    
    public void mudarParaTelaVisualizacaoHospedagens(){
        TelaVisualizarHospedagens tela = new TelaVisualizarHospedagens();
        mudarTela(tela);
    }
    
    public void mudarParaTelaDetalhesHospedagem(){
        TelaDetalhesHospedagem tela = new TelaDetalhesHospedagem();
        mudarTela(tela);
    }
    
    public void mudarParaTelaFavoritasHospede(){
        TelaFavoritasHospede tela = new TelaFavoritasHospede();
        mudarTela(tela);
    }
    
    public void mudarParaTelaRealizarReserva(){
        TelaRealizarReserva tela = new TelaRealizarReserva();
        mudarTela(tela);
    }
    
    public void mudarParaTelaDetalhesReserva(){
        TelaDetalhesReserva tela = new TelaDetalhesReserva();
        mudarTela(tela);
    }
    
    public void mudarParaTelaMinhasReservas(){
        TelaMinhasReservas tela = new TelaMinhasReservas();
        mudarTela(tela);
    }
    
    public void mudarParaTelaReservasPendentes(){
        TelaReservasPendentes tela = new TelaReservasPendentes();
        mudarTela(tela);
    }
    
    public void mudarParaTelaReservasDaHospedagem(){
        TelaReservasDaHospedagem tela = new TelaReservasDaHospedagem();
        mudarTela(tela);
    }
    
    public void mudarParaTelaVisualizarGrupos(){
        TelaVisualizarGrupos tela = new TelaVisualizarGrupos();
        mudarTela(tela);
    }
    
    public void mudarParaTelaGerenciarGrupo(){
        TelaGerenciarGrupo tela = new TelaGerenciarGrupo();
        mudarTela(tela);
    }
    
    public void mudarParaTelaFavoritasGrupo(){
        TelaFavoritasGrupo tela = new TelaFavoritasGrupo();
        mudarTela(tela);
    }
    
    public void mudarParaTelaRankingGrupo(){
        TelaRankingGrupo tela = new TelaRankingGrupo();
        mudarTela(tela);
    }
    
    public void voltarPagina(){
        mudarTela(this.telaAnterior);
    }
    
    public void configurarEstadoMenu(boolean habilitado){
        //Libera os itens do menu conta
        minhaContaMenuItem.setEnabled(habilitado);
        sairMenuItem.setEnabled(habilitado);
        painelDoAnfitriãoMenu.setEnabled(habilitado);
        
        // Libera menus de hospedagem e grupo
        hospedagemMenu.setEnabled(habilitado);
        gruposMenu.setEnabled(habilitado);
        
        loginMenuItem.setEnabled(!habilitado);
    }
    
    public void limparTela(){
        var components = this.getContentPane().getComponents();
        for(Component comp : components){
            if (comp instanceof JPanel)
                this.remove(comp);
        }
    }
    
    private void salvarPaginaAnterior(){
        var components = this.getContentPane().getComponents();
        for(Component comp : components){
            if (comp instanceof JPanel panel)
                this.telaAnterior = panel;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu contaMenu;
    private javax.swing.JMenuItem favoritasGrupoMenuItem;
    private javax.swing.JMenuItem favoritasMenuItem;
    private javax.swing.JMenu gruposMenu;
    private javax.swing.JMenu hospedagemMenu;
    private javax.swing.JMenuItem hospedagensCadastradaMenuItem;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem minhaContaMenuItem;
    private javax.swing.JMenuItem minhasReservasMenuItem;
    private javax.swing.JMenu painelDoAnfitriãoMenu;
    private javax.swing.JMenuItem rankingHospedagensMenuItem;
    private javax.swing.JMenuItem reservasPendentesMenuItem;
    private javax.swing.JMenuItem sairMenuItem;
    private com.mycompany.easytrip.telas.TelaDeLogin telaDeLogin1;
    private javax.swing.JMenuItem verGruposMenuItem;
    private javax.swing.JMenuItem visualizarMenuItem;
    // End of variables declaration//GEN-END:variables
}
